# Generated by Django 3.1.1 on 2020-09-07 06:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CritterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critter_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hemisphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemisphere', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='CritterTimeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critters.critter')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='critters.hour')),
            ],
        ),
        migrations.CreateModel(
            name='CritterMonthHemisphereRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critters.critter')),
                ('hemisphere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='critters.hemisphere')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='critters.month')),
            ],
        ),
        migrations.AddField(
            model_name='critter',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='critters.location'),
        ),
        migrations.AddField(
            model_name='critter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='critters.crittertype'),
        ),
    ]
