# Generated by Django 3.1.1 on 2020-09-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0002_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critter',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='critters.location'),
        ),
    ]
